name: Selenium Tests CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  login-correct:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run Login Correct Test
      run: mvn -B clean test -Dtest=LoginTest#testLoginCorrect -Dheadless=true

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports-correct
        path: target/surefire-reports/

    - name: Publish Test Report Correct
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Login Correct Results
        path: target/surefire-reports/*.xml
        reporter: java-junit

  login-incorrect:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run Login Incorrect Test
      run: mvn -B clean test -Dtest=LoginTest#testLoginIncorrect -Dheadless=true

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports-incorrect
        path: target/surefire-reports/

    - name: Publish Test Report Incorrect
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Login Incorrect Results
        path: target/surefire-reports/*.xml
        reporter: java-junit